######################################################################
##
## Filename: tb.udo
## Created on: Wed Jan 07 10:50:04 Maroc (heure d’été) 2026
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
